INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('EVGA 2080ti', 'C01', 699.99, 'Mid ranged graphics card', 'GPUs', 'EVGA');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Corsair Vengeance LPX 16GB', 'C02', 79.99, '16GB DDR4 RAM, 3200MHz', 'Memory', 'Corsair');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Samsung 970 EVO Plus 1TB', 'C03', 139.99, '1TB NVMe SSD with high speed', 'Storage', 'Samsung');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('ASUS ROG Strix B550-F', 'C04', 199.99, 'AM4 ATX motherboard with WiFi', 'Motherboards', 'ASUS');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Cooler Master MasterLiquid ML240L', 'C05', 69.99, '240mm RGB liquid CPU cooler', 'Cooling', 'Cooler Master');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Seagate Barracuda 2TB', 'C06', 59.99, '2TB HDD for data storage', 'Storage', 'Seagate');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Razer DeathAdder V2', 'C07', 49.99, 'Ergonomic gaming mouse with RGB', 'Peripherals', 'Razer');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Logitech G Pro Mechanical Keyboard', 'C08', 129.99, 'Compact and responsive gaming keyboard', 'Peripherals', 'Logitech');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('NZXT H510', 'C09', 69.99, 'Mid tower ATX case with tempered glass', 'Cases', 'NZXT');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Gigabyte AORUS 3080', 'C10', 799.99, 'High performance graphics card', 'GPUs', 'Gigabyte');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Intel Core i9-11900K', 'C11', 499.99, '11th Gen Intel processor with 8 cores', 'CPUs', 'Intel');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('AMD Ryzen 5 5600X', 'C12', 299.99, '6-core processor with excellent performance', 'CPUs', 'AMD');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Thermaltake Toughpower 750W', 'C13', 109.99, '750W power supply with high efficiency', 'PSUs', 'Thermaltake');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('BenQ ZOWIE XL2411P', 'C14', 299.99, '24 inch gaming monitor with 144Hz', 'Monitors', 'BenQ');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Dell UltraSharp U2720Q', 'C15', 599.99, '27 inch 4K monitor with USB-C', 'Monitors', 'Dell');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Crucial MX500 500GB', 'C16', 54.99, '500GB SATA SSD for quick storage', 'Storage', 'Crucial');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('TP-Link Archer AX50', 'C17', 129.99, 'Dual band Wi-Fi 6 router', 'Networking', 'TP-Link');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Anker USB-C Hub', 'C18', 39.99, 'Multiport USB-C adapter for laptops', 'Accessories', 'Anker');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Microsoft Surface Pro 7', 'C19', 749.99, '2-in-1 laptop with detachable keyboard', 'Laptops', 'Microsoft');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Apple MacBook Air M1', 'C20', 999.99, 'Lightweight laptop with M1 chip', 'Laptops', 'Apple');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Logitech C920 Webcam', 'C21', 69.99, 'Full HD webcam for streaming', 'Peripherals', 'Logitech');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('ASUS TUF Gaming A15', 'C22', 1199.99, 'Gaming laptop with Ryzen 5 and GTX 1660 Ti', 'Laptops', 'ASUS');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('HyperX Cloud II', 'C23', 99.99, 'Gaming headset with virtual 7.1 surround sound', 'Peripherals', 'HyperX');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('MSI MAG Forge 100M', 'C24', 69.99, 'ATX case with RGB fans', 'Cases', 'MSI');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('PNY XLR8 Gaming SSD 1TB', 'C25', 139.99, '1TB external SSD for fast storage', 'Storage', 'PNY');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('ADATA XPG Gammix D30 16GB', 'C26', 79.99, '16GB DDR4 RAM, 3000MHz', 'Memory', 'ADATA');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Cooler Master MasterBox Q300L', 'C27', 59.99, 'Micro-ATX case with excellent airflow', 'Cases', 'Cooler Master');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Seasonic Focus GX-650', 'C28', 109.99, '650W 80+ Gold power supply', 'PSUs', 'Seasonic');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('G.Skill Ripjaws V 32GB', 'C29', 139.99, '32GB DDR4 RAM, 3200MHz', 'Memory', 'G.Skill');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Radeon RX 6800', 'C30', 649.99, 'High-end graphics card from AMD', 'GPUs', 'AMD');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Logitech G903 LIGHTSPEED', 'C31', 149.99, 'Wireless gaming mouse with RGB', 'Peripherals', 'Logitech');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Lenovo Legion 5', 'C32', 1299.99, 'Gaming laptop with Ryzen 7 and RTX 2060', 'Laptops', 'Lenovo');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Netgear Nighthawk RAX200', 'C33', 499.99, 'Tri-band Wi-Fi 6 router', 'Networking', 'Netgear');
INSERT INTO products(itemname, itemsku, itemprice, itemdesc, itemcat, "userListed") VALUES ('Corsair 4000D Airflow', 'C34', 89.99, 'Mid-tower case with excellent airflow', 'Cases', 'Corsair');
